version: 2.1

orbs:
  node: circleci/node@2.0.3
  puppeteer: threetreeslight/puppeteer@0.1.2

jobs:
  build-and-verify:
    executor:
      name: node/default
      tag: '10.18.1'
    steps:
      - checkout
      - node/install-packages
      - puppeteer/install
      - run:
          name: Format Checking
          command: npm run format:check
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit Testing
          command: npm run test:unit -- --coverage
      - run:
          name: End-to-End Testing
          command: npm run test:e2e

workflows:
  build-and-verify:
    jobs:
      - build-and-verify
