version: 2.1

orbs:
  node: circleci/node@4.0.1

jobs:
  build:
    executor:
      name: node/default
      tag: '12.18.4'
    steps:
      - checkout
      - node/install-packages
      # Save workspace for subsequent jobs
      - persist_to_workspace:
          root: .
          paths:
            - .

  run-static-checks:
    executor:
      name: node/default
      tag: '12.18.4'
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Format Checking
          command: npm run format:check
      - run:
          name: Linting
          command: npm run lint

  unit-test:
    executor:
      name: node/default
      tag: '12.18.4'
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      - run:
          name: Unit Testing
          command: npm run test:unit -- -- --ci --maxWorkers 2

  integration-e2e-test:
    executor:
      name: node/default
      tag: '12.18.4'
    steps:
      # Reuse the workspace from the build job
      - attach_workspace:
          at: .
      # Copied from https://circleci.com/orbs/registry/orb/threetreeslight/puppeteer.
      # Not using this Orb directly to prevent re-downloading Chromium which was already
      # done in the previous step.
      - run:
          name: Install Headless Chrome Dependencies
          command: |
            sudo apt update -qq
            sudo apt install -yqq libgbm-dev
      - run:
          name: Configure local host mapping
          command: echo 127.0.0.1 a8c-abacus-local | sudo tee -a /etc/hosts
      - run:
          name: Integration Testing
          command: npm run test:integration -- --ci
      - run:
          name: End-to-End Testing
          command: npm run test:e2e -- --ci

workflows:
  build-and-test:
    jobs:
      - build
      - run-static-checks:
          requires:
            - build
      - unit-test:
          requires:
            - build
      - integration-e2e-test:
          requires:
            - build
